language: node_js
node_js:
  - stable
cache:
  directories:
  - node_modules
script:
  - yarn run build
  - yarn run build:storybook
  - yarn test:coverage

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: .out
  target_branch: master
  on:
    branch: source
